spring.application.name=Literalura
spring.datasource.url=jdbc:postgresql://localhost/litealura
spring.datasource.username=postgres
spring.datasource.password=hola12
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update